import React, { useEffect, useMemo, useState } from 'react';
import { BarChart3, Database, FolderOpen, LayoutDashboard, Plus, RefreshCw, Save, Search, Settings2, Trash2, Upload, ZoomIn, ZoomOut, Camera, ClipboardList, Download } from 'lucide-react';

type CenterTab = 'dashboard' | 'projects' | 'files' | 'delivery' | 'settings';
type BreakdownRow = { size: string; color: string; quantity: number; destination: string };
const isDesktop = () => typeof window !== 'undefined' && Boolean(window.rubaDesktop);

export default function IndustrialCenter({ onBack, onLoadProject, projectPayload, initialTab = 'dashboard', showTabs = true }: { onBack: () => void; onLoadProject?: (project: any) => Promise<void> | void; projectPayload?: any; initialTab?: CenterTab; showTabs?: boolean }) {
  const [tab, setTab] = useState<CenterTab>(initialTab);
  useEffect(() => { setTab(initialTab); }, [initialTab]);
  const [summary, setSummary] = useState({ projects: 0, packingLists: 0, files: 0, deliveryPlans: 0, breakdownRows: 0 });
  const [projects, setProjects] = useState<any[]>([]);
  const [files, setFiles] = useState<any[]>([]);
  const [search, setSearch] = useState('');
  const [storageRoot, setStorageRoot] = useState('');
  const [projectName, setProjectName] = useState('');
  const [customer, setCustomer] = useState('');
  const [selectedProjectId, setSelectedProjectId] = useState('');
  const [planName, setPlanName] = useState('');
  const [planId, setPlanId] = useState('');
  const [rows, setRows] = useState<BreakdownRow[]>([{ size: '', color: '', quantity: 0, destination: '' }]);
  const [zoom, setZoom] = useState(() => Number(localStorage.getItem('ruba_ui_zoom') || 100));
  const [accent, setAccent] = useState(() => localStorage.getItem('ruba_accent') || '#0f766e');
  const [message, setMessage] = useState('');

  const refresh = async () => {
    if (!isDesktop()) return;
    const api = window.rubaDesktop!;
    const [nextSummary, nextProjects, nextFiles, root] = await Promise.all([api.dbSummary(), api.listProjects(search), api.listFiles({ search }), api.getStorageRoot()]);
    setSummary(nextSummary); setProjects(nextProjects); setFiles(nextFiles); setStorageRoot(root);
    if (!selectedProjectId && nextProjects[0]) setSelectedProjectId(nextProjects[0].id);
  };
  useEffect(() => { refresh().catch(() => setMessage('Le centre local sera disponible dans la version desktop.')); }, [search]);
  useEffect(() => { document.body.style.zoom = `${zoom / 100}`; document.documentElement.style.setProperty('--ruba-accent', accent); return () => { document.body.style.zoom = '1'; }; }, []);

  const applyZoom = (value: number) => { const next = Math.max(80, Math.min(125, value)); setZoom(next); localStorage.setItem('ruba_ui_zoom', String(next)); document.body.style.zoom = `${next / 100}`; };
  const saveAccent = (value: string) => { setAccent(value); localStorage.setItem('ruba_accent', value); document.documentElement.style.setProperty('--ruba-accent', value); };
  const createProject = async () => { if (!isDesktop() || !projectName.trim()) return; const saved = await window.rubaDesktop!.saveProject({ name: projectName.trim(), customer, status: 'draft', payload: projectPayload || {} }); setProjectName(''); setCustomer(''); setSelectedProjectId(saved.id); setMessage('Travail enregistré dans SQLite.'); await refresh(); };
  const chooseRoot = async () => { if (!isDesktop()) return; const next = await window.rubaDesktop!.chooseStorageRoot(); if (next) { setStorageRoot(next); setMessage('Dossier de stockage modifié.'); } };
  const capture = async () => { if (!isDesktop()) return; const result = await window.rubaDesktop!.captureWindow(); if (!result.canceled) setMessage(`Capture enregistrée : ${result.filePath}`); };
  const addRow = () => setRows(prev => [...prev, { size: '', color: '', quantity: 0, destination: '' }]);
  const updateRow = (index: number, key: keyof BreakdownRow, value: string) => setRows(prev => prev.map((row, rowIndex) => rowIndex === index ? { ...row, [key]: key === 'quantity' ? Number(value || 0) : value } : row));
  const savePlan = async () => { if (!isDesktop() || !selectedProjectId || !planName.trim()) { setMessage('Choisissez un travail et renseignez le nom du Delivery Plan.'); return; } const plan = await window.rubaDesktop!.saveDeliveryPlan({ id: planId || undefined, projectId: selectedProjectId, planName, payload: { rows } }); setPlanId(plan.id); await window.rubaDesktop!.replaceBreakdown({ deliveryPlanId: plan.id, rows }); setMessage('Delivery Plan et breakdown enregistrés dans SQLite.'); await refresh(); };
  const tabs = useMemo(() => [['dashboard', 'Dashboard'], ['projects', 'Travaux'], ['files', 'Fichiers Excel'], ['delivery', 'Delivery Plan'], ['settings', 'Paramètres']] as const, []);

  return <section className="flex-1 min-h-0 overflow-auto rounded-2xl border border-slate-200 bg-white shadow-sm" style={{ ['--ruba-accent' as any]: accent }}>
    <div className="sticky top-0 z-10 flex flex-wrap items-center justify-between gap-3 border-b border-slate-200 bg-white/95 px-5 py-4 backdrop-blur"><div><p className="text-[10px] font-black uppercase tracking-[0.2em] text-slate-500">Ruba Industrial Workspace</p><h2 className="text-xl font-black text-slate-900">Centre de pilotage</h2></div><div className="flex flex-wrap items-center gap-2"><button onClick={() => applyZoom(zoom - 5)} className="rounded-lg border border-slate-200 bg-white p-2 text-slate-700 hover:bg-slate-50" title="Réduire le zoom"><ZoomOut size={16}/></button><span className="min-w-12 text-center text-xs font-bold text-slate-600">{zoom}%</span><button onClick={() => applyZoom(zoom + 5)} className="rounded-lg border border-slate-200 bg-white p-2 text-slate-700 hover:bg-slate-50" title="Augmenter le zoom"><ZoomIn size={16}/></button><button onClick={capture} className="flex items-center gap-2 rounded-lg bg-slate-900 px-3 py-2 text-xs font-bold text-white hover:bg-slate-700"><Camera size={15}/> Capture</button><button onClick={onBack} className="rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold text-slate-700 hover:bg-slate-50">Retour au colisage</button></div></div>
    {showTabs && <div className="flex gap-2 overflow-x-auto border-b border-slate-100 px-5 py-3">{tabs.map(([id, label]) => <button key={id} onClick={() => setTab(id)} className={`flex items-center gap-2 rounded-xl px-3 py-2 text-xs font-bold transition ${tab === id ? 'text-white shadow-sm' : 'bg-slate-50 text-slate-600 hover:bg-slate-100'}`} style={tab === id ? { backgroundColor: accent } : undefined}><span className="h-2 w-2 rounded-full bg-current" />{label}</button>)}</div>}
    {message && <div className="mx-5 mt-4 rounded-lg border border-emerald-200 bg-emerald-50 px-3 py-2 text-xs font-semibold text-emerald-800">{message}</div>}

    {tab === 'dashboard' && <div className="grid gap-4 p-5 md:grid-cols-5">{[['Travaux', summary.projects], ['Packing Lists', summary.packingLists], ['Fichiers', summary.files], ['Delivery Plans', summary.deliveryPlans], ['Lignes breakdown', summary.breakdownRows]].map(([label, value]: any) => <div key={label} className="rounded-2xl border border-slate-200 bg-slate-50 p-5"><span className="inline-block h-3 w-3 rounded-full" style={{ backgroundColor: accent }} /><p className="mt-4 text-xs font-bold uppercase tracking-wider text-slate-500">{label}</p><p className="mt-1 text-3xl font-black text-slate-900">{value}</p></div>)}<div className="md:col-span-4 rounded-2xl border border-slate-200 p-5"><div className="flex items-center justify-between"><h3 className="font-black text-slate-900">Vue opérationnelle</h3><button onClick={() => refresh()} className="flex items-center gap-2 rounded-lg border px-3 py-2 text-xs font-bold"><RefreshCw size={14}/> Actualiser</button></div><p className="mt-3 text-sm text-slate-600">Travaux, exports Excel, Delivery Plans et breakdowns sont centralisés dans SQLite. Les actions importantes sont conservées dans le journal d’audit local.</p></div></div>}

    {tab === 'projects' && <div className="space-y-4 p-5"><div className="flex flex-wrap gap-2"><input value={projectName} onChange={e => setProjectName(e.target.value)} placeholder="Nom du travail" className="rounded-lg border px-3 py-2 text-sm"/><input value={customer} onChange={e => setCustomer(e.target.value)} placeholder="Client" className="rounded-lg border px-3 py-2 text-sm"/><button onClick={createProject} className="flex items-center gap-2 rounded-lg px-4 py-2 text-xs font-bold text-white" style={{ backgroundColor: accent }}><Plus size={14}/> Nouveau travail</button></div><div className="overflow-auto rounded-xl border"><table className="w-full text-left text-sm"><thead className="bg-slate-900 text-xs uppercase text-white"><tr><th className="px-4 py-3">Nom</th><th className="px-4 py-3">Client</th><th className="px-4 py-3">Statut</th><th className="px-4 py-3">Dernière mise à jour</th><th className="px-4 py-3 text-right">Actions</th></tr></thead><tbody>{projects.map(p => <tr key={p.id} className="border-t"><td className="px-4 py-3 font-bold">{p.name}</td><td className="px-4 py-3">{p.customer}</td><td className="px-4 py-3">{p.status}</td><td className="px-4 py-3 text-slate-500">{new Date(p.updated_at).toLocaleString()}</td><td className="px-4 py-3"><div className="flex justify-end gap-3"><button onClick={async () => { try { const full = await window.rubaDesktop?.getProject(p.id); if (!full) throw new Error('Projet introuvable.'); await onLoadProject?.(full); setMessage(`Projet chargé : ${p.name}`); } catch (error: any) { setMessage(`Erreur de chargement : ${error?.message || error}`); } }} className="rounded-lg border border-teal-200 px-3 py-1.5 text-xs font-bold text-teal-700">Charger</button><button onClick={async () => { if (!window.confirm(`Supprimer le projet « ${p.name} » ?`)) return; await window.rubaDesktop?.deleteProject(p.id); refresh(); }} className="text-rose-600"><Trash2 size={15}/></button></div></td></tr>)}</tbody></table></div></div>}

    {tab === 'files' && <div className="space-y-4 p-5"><div className="flex items-center gap-2"><div className="flex flex-1 items-center gap-2 rounded-lg border px-3 py-2"><Search size={15} className="text-slate-400"/><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Filtrer les fichiers et travaux" className="w-full text-sm outline-none"/></div><button onClick={refresh} className="rounded-lg border p-2"><RefreshCw size={16}/></button><button onClick={async () => { const imported = await window.rubaDesktop?.importFile({ fileKind: 'excel' }); if (imported) { setMessage(`Fichier importé : ${imported.name}`); await refresh(); } }} className="flex items-center gap-2 rounded-lg px-3 py-2 text-xs font-bold text-white" style={{ backgroundColor: accent }}><Upload size={14}/> Importer Excel</button></div><div className="overflow-auto rounded-xl border"><table className="w-full text-left text-sm"><thead className="bg-slate-900 text-xs uppercase text-white"><tr><th className="px-4 py-3">Fichier</th><th className="px-4 py-3">Type</th><th className="px-4 py-3">Travail</th><th className="px-4 py-3">Chemin</th></tr></thead><tbody>{files.map(f => <tr key={f.id} className="border-t"><td className="px-4 py-3 font-bold">{f.name}</td><td className="px-4 py-3">{f.file_kind}</td><td className="px-4 py-3">{f.project_name || '—'}</td><td className="max-w-md truncate px-4 py-3 text-slate-500">{f.stored_path}</td></tr>)}</tbody></table></div></div>}

    {tab === 'delivery' && <div className="space-y-4 p-5"><div className="flex flex-wrap items-center gap-2 rounded-xl border border-slate-200 bg-slate-50 p-4"><select value={selectedProjectId} onChange={e => setSelectedProjectId(e.target.value)} className="rounded-lg border bg-white px-3 py-2 text-sm"><option value="">Choisir un travail</option>{projects.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select><input value={planName} onChange={e => setPlanName(e.target.value)} placeholder="Nom du Delivery Plan" className="rounded-lg border px-3 py-2 text-sm"/><button onClick={savePlan} className="flex items-center gap-2 rounded-lg px-4 py-2 text-xs font-bold text-white" style={{ backgroundColor: accent }}><Save size={14}/> Enregistrer le plan</button></div><div className="overflow-auto rounded-xl border"><table className="w-full text-left text-sm"><thead className="bg-slate-900 text-xs uppercase text-white"><tr><th className="px-3 py-3">Taille</th><th className="px-3 py-3">Couleur</th><th className="px-3 py-3">Quantité</th><th className="px-3 py-3">Destination</th></tr></thead><tbody>{rows.map((row, index) => <tr key={index} className="border-t"><td className="p-2"><input value={row.size} onChange={e => updateRow(index, 'size', e.target.value)} className="w-full rounded border px-2 py-1" placeholder="M"/></td><td className="p-2"><input value={row.color} onChange={e => updateRow(index, 'color', e.target.value)} className="w-full rounded border px-2 py-1" placeholder="Noir"/></td><td className="p-2"><input type="number" min="0" value={row.quantity} onChange={e => updateRow(index, 'quantity', e.target.value)} className="w-full rounded border px-2 py-1"/></td><td className="p-2"><input value={row.destination} onChange={e => updateRow(index, 'destination', e.target.value)} className="w-full rounded border px-2 py-1" placeholder="Destination"/></td></tr>)}</tbody></table></div><div className="flex gap-2"><button onClick={addRow} className="flex items-center gap-2 rounded-lg border px-3 py-2 text-xs font-bold"><Plus size={14}/> Ajouter une ligne</button><span className="flex items-center gap-2 text-xs text-slate-500"><Download size={14}/> Export breakdown à relier au format Excel</span></div></div>}

    {tab === 'settings' && <div className="space-y-5 p-5"><div className="rounded-2xl border border-slate-200 p-5"><h3 className="font-black">Stockage local</h3><p className="mt-2 break-all text-xs text-slate-500">{storageRoot || 'Navigateur : stockage local du profil'}</p><button onClick={chooseRoot} className="mt-3 flex items-center gap-2 rounded-lg border px-4 py-2 text-xs font-bold"><FolderOpen size={14}/> Modifier le dossier</button></div><div className="rounded-2xl border border-slate-200 p-5"><h3 className="font-black">Thème et couleurs</h3><div className="mt-4 flex items-center gap-3"><input type="color" value={accent} onChange={e => saveAccent(e.target.value)} className="h-10 w-14 cursor-pointer rounded border"/><span className="text-sm font-semibold text-slate-700">Couleur principale des boutons et rubans</span><button onClick={() => saveAccent('#0f766e')} className="flex items-center gap-2 rounded-lg border px-3 py-2 text-xs font-bold"><Save size={14}/> Réinitialiser</button></div></div></div>}
  </section>;
}
